Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2018-09, with the labels that each got.

#1956 [New] Support shorthand fragment syntax
  lib/rules/jsx-child-element-spacing.js
  lib/rules/jsx-closing-tag-location.js
  lib/rules/jsx-curly-brace-presence.js
  lib/rules/jsx-curly-spacing.js
  lib/rules/jsx-filename-extension.js
  lib/rules/jsx-indent.js
  lib/rules/jsx-max-depth.js
  lib/rules/jsx-one-expression-per-line.js
  lib/rules/jsx-uses-react.js
  lib/rules/jsx-wrap-multilines.js
  lib/rules/no-unescaped-entities.js
  lib/util/Components.js
  lib/util/jsx.js
  tests/lib/rules/jsx-child-element-spacing.js
  tests/lib/rules/jsx-closing-tag-location.js
  tests/lib/rules/jsx-curly-brace-presence.js
  tests/lib/rules/jsx-curly-spacing.js
  tests/lib/rules/jsx-filename-extension.js
  tests/lib/rules/jsx-indent.js
  tests/lib/rules/jsx-max-depth.js
  tests/lib/rules/jsx-no-comment-textnodes.js
  tests/lib/rules/jsx-no-literals.js
  tests/lib/rules/jsx-one-expression-per-line.js
  tests/lib/rules/jsx-uses-react.js
  tests/lib/rules/jsx-wrap-multilines.js
  tests/lib/rules/no-unescaped-entities.js
  tests/lib/rules/prop-types.js
Labels: enhancement

#1977 Fix sort-prop-types string property order
  lib/rules/sort-prop-types.js
  tests/lib/rules/sort-prop-types.js
Labels: bug

#1989 Fix `no-this-in-sfc` rule behavior for arrow functions inside a class field
  lib/rules/no-this-in-sfc.js
  lib/util/Components.js
  tests/lib/rules/no-this-in-sfc.js
Labels: bug

#2002 `display-name` docs: mention default `ignoreTranspilerName` value
  docs/rules/display-name.md
Labels: documentation

#1995 Fix `no-this-in-sfc` for class properties
  lib/util/Components.js
  lib/util/ast.js
  tests/lib/rules/no-this-in-sfc.js
Labels: bug
