Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2018-03, with the labels that each got.

#1681 Update no-unused-prop-types rule for new React class component lifecycles
  lib/rules/no-unused-prop-types.js
  tests/lib/rules/no-unused-prop-types.js
Labels: enhancement

#1699 [Fix] `react/jsx-no-bind` Add props to example
  docs/rules/jsx-no-bind.md
Labels: documentation

#1718 [fix] Allow whitespace jsx container in jsx-curly-brace-presence (fixes: #1717)
  docs/rules/jsx-curly-brace-presence.md
  lib/rules/jsx-curly-brace-presence.js
  tests/lib/rules/jsx-curly-brace-presence.js
Labels: bug

#1671 Allow custom PropType classes with no-typos rule
  lib/rules/no-typos.js
  tests/lib/rules/no-typos.js
Labels: bug

#1723 handle ternary operation for jsx-no-bind
  lib/rules/jsx-no-bind.js
  tests/lib/rules/jsx-no-bind.js
Labels: bug

#1734 Fix typo
  docs/rules/jsx-max-depth.md
Labels: documentation

#1733 Issue #1724 support for Flow generic PropTypes declaration in require-default-props rule
  lib/rules/require-default-props.js
  tests/lib/rules/require-default-props.js
Labels: bug, flow
