Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2018-10, with the labels that each got.

#2012 Fix fixer for jsx-sort-comp in case of more than 10 props
  lib/rules/jsx-sort-props.js
  tests/lib/rules/jsx-sort-props.js
Labels: bug

#2008 Adding option to print node value
  lib/rules/jsx-no-literals.js
  tests/lib/rules/jsx-no-literals.js
Labels: enhancement, rule

#2015 add more escape examples
  docs/rules/no-unescaped-entities.md
Labels: documentation

#1978 [New] Support "detect" option for React version setting
  .gitignore
  lib/util/version.js
  package.json
  tests/fixtures/version/detect-version/node_modules/react/index.js
  tests/fixtures/version/detect-version/node_modules/react/package.json
  tests/util/version.js
Labels: enhancement

#1984 jsx-wrap-multilines now catches single missing newlines
  lib/rules/jsx-wrap-multilines.js
  tests/lib/rules/jsx-wrap-multilines.js
Labels: bug
