Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2018-07, with the labels that each got.

#1860 Stop crashing on undefined or null properties in flow intersection
  lib/rules/prop-types.js
  tests/lib/rules/prop-types.js
Labels: bug, flow

#1880 add missing urls
  lib/rules/jsx-max-depth.js
  lib/rules/jsx-sort-default-props.js
Labels: documentation

#1883 Fix `reservedFirst` for `jsx-sort-props` rule
  lib/rules/jsx-sort-props.js
  tests/lib/rules/jsx-sort-props.js
Labels: bug

#1858 sort-comp Allow methods to belong to any matching group.
  lib/rules/sort-comp.js
  package.json
  tests/lib/rules/sort-comp.js
Labels: bug

#1891 Add fixer for sort-prop-types
  docs/rules/sort-prop-types.md
  lib/rules/sort-prop-types.js
  tests/lib/rules/sort-prop-types.js
Labels: enhancement

#1890 Handle member expressions in jsx-props-no-multi-spaces
  lib/rules/jsx-props-no-multi-spaces.js
  tests/lib/rules/jsx-props-no-multi-spaces.js
Labels: bug

#1898 Additional test case for literals as prop keys in prop-types
  tests/lib/rules/prop-types.js
Labels: flow

#1905 [Fix] Handle inline Flow type in boolean-prop-naming
  lib/rules/boolean-prop-naming.js
  tests/lib/rules/boolean-prop-naming.js
Labels: bug, flow

#1907 Make Components.get ignore components with confidence = 0
  lib/util/Components.js
  tests/lib/rules/destructuring-assignment.js
Labels: bug
