Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2018-12, with the labels that each got.

#2064 Change naming from singular defaultProp to plural defaultProps
  lib/rules/require-default-props.js
  tests/lib/rules/require-default-props.js
Labels: documentation

#2067 Remove debatable statement on perf in jsx-no-bind
  docs/rules/jsx-no-bind.md
Labels: documentation

#2086 Handle JSX attribute indentation in jsx-indent
  docs/rules/jsx-indent.md
  lib/rules/jsx-indent.js
  lib/util/ast.js
  tests/lib/rules/jsx-indent.js
Labels: enhancement, rule

#2090 Fix noMethodSetState docsUrl's
  lib/util/makeNoMethodSetStateRule.js
Labels: documentation

#2085 Fix: no-array-index-key not working in React.Children methods
  docs/rules/no-array-index-key.md
  lib/rules/no-array-index-key.js
  tests/lib/rules/no-array-index-key.js
Labels: bug

#2089 Support detecting React.forwardRef/React.memo
  lib/rules/void-dom-elements-no-children.js
  lib/util/Components.js
  lib/util/usedPropTypes.js
  tests/lib/rules/prop-types.js
Labels: enhancement, react 16

#2032 `jsx-fragments`: improve message text
  lib/rules/jsx-fragments.js
  package.json
  tests/lib/rules/jsx-fragments.js
Labels: documentation

#1824 Fix depth of JSX siblings in a JSXEpressionContainer
  lib/rules/jsx-max-depth.js
  tests/lib/rules/jsx-max-depth.js
Labels: bug

#2099 Fix false positives inside lifecycle methods
  lib/util/usedPropTypes.js
  tests/lib/rules/prop-types.js
Labels: bug
