Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2018-02, with the labels that each got.

#1260 [New] `jsx-max-depth`: validate a specific depth for JSX
  docs/rules/jsx-max-depth.md
  index.js
  lib/rules/jsx-max-depth.js
  tests/lib/rules/jsx-max-depth.js
Labels: new rule

#1698 Allow crossOrigin on audio elements
  lib/rules/no-unknown-property.js
  tests/lib/rules/no-unknown-property.js
Labels: bug

#1701 Handle isRequired for boolean-prop-naming
  lib/rules/boolean-prop-naming.js
  tests/lib/rules/boolean-prop-naming.js
Labels: bug

#1703 [Docs] Add missing rule to readme
  README.md
Labels: documentation

#1704 Fix broken link in README
  README.md
Labels: documentation
