Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2018-05, with the labels that each got.

#1786 Hotfix - fix no-deprecated bug
  lib/rules/no-deprecated.js
  lib/util/version.js
  tests/lib/rules/no-deprecated.js
Labels: bug

#1794 Add a when not to use case to forbid-foreign-prop-types
  docs/rules/forbid-foreign-prop-types.md
Labels: documentation

#1796 guard against accidental anonymous react imports
  lib/rules/no-typos.js
  tests/lib/rules/no-typos.js
Labels: bug

#1795 sort-comp: enforcing static lifecycle methods order
  lib/rules/sort-comp.js
  tests/lib/rules/sort-comp.js
Labels: bug

#1784 Target blank dynamic link should fail
  docs/rules/jsx-no-target-blank.md
  lib/rules/jsx-no-target-blank.js
  tests/lib/rules/jsx-no-target-blank.js
Labels: enhancement

#1755 Add jsx-props-no-multi-spaces rule
  README.md
  docs/rules/jsx-props-no-multi-spaces.md
  index.js
  lib/rules/jsx-props-no-multi-spaces.js
  tests/lib/rules/jsx-props-no-multi-spaces.js
Labels: accepted, new rule

#1729 Add JSX prop alignment based on the first prop & between-prop space consistency
  docs/rules/jsx-indent-props.md
  lib/rules/jsx-indent-props.js
  tests/lib/rules/jsx-indent-props.js
Labels: enhancement
