Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2018-08, with the labels that each got.

#1914 Add a helper function for determining function-like expressions
  lib/rules/display-name.js
  lib/rules/no-array-index-key.js
  lib/rules/no-unused-prop-types.js
  lib/rules/require-render-return.js
  lib/rules/sort-comp.js
  lib/util/ast.js
  tests/lib/rules/no-typos.js
Labels: enhancement

#1909 Ignore class properties in destructuring-assignment
  docs/rules/destructuring-assignment.md
  lib/rules/destructuring-assignment.js
  tests/lib/rules/destructuring-assignment.js
Labels: enhancement

#1918 Update jsx-props-no-multi-spaces.md
  docs/rules/jsx-props-no-multi-spaces.md
Labels: documentation

#1924 [New] Add allow option to jsx-one-expression-per-line
  docs/rules/jsx-one-expression-per-line.md
  lib/rules/jsx-one-expression-per-line.js
  tests/lib/rules/jsx-one-expression-per-line.js
Labels: enhancement

#1897 Rule sort-prop-types add noSortAlphabetically
  docs/rules/sort-prop-types.md
  lib/rules/sort-prop-types.js
  tests/lib/rules/sort-prop-types.js
Labels: enhancement

#1932 [Fix] stop crashing when assigning to propTypes
  lib/util/propTypes.js
  tests/lib/rules/no-unused-prop-types.js
  tests/lib/rules/prop-types.js
Labels: bug

#1953 Update jsx-no-target-blank.md
  docs/rules/jsx-no-target-blank.md
Labels: documentation
