Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-12, with the labels that each got.

#2521 fix[jsx-curly-brace-presence] Fix error related to tag line breaks
  lib/rules/jsx-curly-brace-presence.js
  tests/lib/rules/jsx-curly-brace-presence.js
Labels: bug

#977 Bug Repro: Unused PropTypes detects flow destructuring
  tests/lib/rules/no-unused-prop-types.js
Labels: bug, help wanted

#2535 Fix rule name reference in "Rule Options" section of jsx-first-prop-new-line.md
  docs/rules/jsx-first-prop-new-line.md
Labels: documentation

#1155 Prevent adjacent inline elements not separated by whitespace.
  CHANGELOG.md
  docs/rules/no-adjacent-inline-elements.md
  index.js
  lib/rules/no-adjacent-inline-elements.js
  tests/lib/rules/no-adjacent-inline-elements.js
Labels: new rule
