Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-10, with the labels that each got.

#2418 update grammar for no-access-state-in-setstate.md
  docs/rules/no-access-state-in-setstate.md
Labels: documentation

#2426 fix`jsx-curly-brace-presence`: bail out checks when JSXElements are passed as props
  lib/rules/jsx-curly-brace-presence.js
Labels: bug

#2443 [docs] `jsx-no-bind`: add section about React Hooks
  docs/rules/jsx-no-bind.md
Labels: documentation

#2450 Update no-unused-prop-types.md
  docs/rules/no-unused-prop-types.md
Labels: documentation

#2449 Allow explicit spread of props
  docs/rules/jsx-props-no-spreading.md
  lib/rules/jsx-props-no-spreading.js
  tests/lib/rules/jsx-props-no-spreading.js
Labels: new rule

#2453 Fix minor typo in README
  README.md
Labels: documentation

#2438 Add section about overriding for trusted links
  docs/rules/jsx-no-target-blank.md
Labels: documentation

#2446 [Fix] Support Flow type spread
  lib/rules/prop-types.js
  lib/util/ast.js
  lib/util/propTypes.js
  tests/lib/rules/default-props-match-prop-types.js
  tests/lib/rules/no-unused-prop-types.js
  tests/lib/rules/prop-types.js
Labels: flow

#2465 Update jsx-first-prop-new-line.md
  docs/rules/jsx-first-prop-new-line.md
Labels: documentation
