Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-08, with the labels that each got.

#2367 fix(jsx-key): update error message and docs
  docs/rules/jsx-key.md
  lib/rules/jsx-key.js
  tests/lib/rules/jsx-key.js
Labels: bug, documentation

#2385 Require Optimization breaks when using arrow function Fix
  lib/rules/require-optimization.js
  tests/lib/rules/require-optimization.js
Labels: bug

#2392 2390 - fix incorrect formatting in jsx-wrap-multilines
  lib/rules/jsx-wrap-multilines.js
  tests/lib/rules/jsx-wrap-multilines.js
Labels: bug

#2391 2381-fix camelCase error in jsx-sort-props
  lib/rules/jsx-sort-props.js
  tests/lib/rules/jsx-sort-props.js
Labels: bug

#2380 Add allowed strings, jsx-no-literals
  docs/rules/jsx-no-literals.md
  lib/rules/jsx-no-literals.js
  tests/lib/rules/jsx-no-literals.js
Labels: enhancement
