Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-05, with the labels that each got.

#2256 [fix] `jsx-props-no-multi-spaces`: support generic components (ts)
  lib/rules/jsx-props-no-multi-spaces.js
  tests/lib/rules/jsx-props-no-multi-spaces.js
Labels: typescript

#2262 Add missing `react/prefer-read-only-props` link
  README.md
Labels: documentation

#1823 Support proptype shape in a variable for sortShapeProp
  lib/rules/sort-prop-types.js
  tests/lib/rules/sort-prop-types.js
Labels: enhancement, rule

#1613 no-did-mount-set-state with cDU or cDM as ClassProperties
  lib/util/makeNoMethodSetStateRule.js
  tests/lib/rules/no-did-mount-set-state.js
  tests/lib/rules/no-did-update-set-state.js
Labels: bug

#2295 Add missing quotes to rule options example
  docs/rules/forbid-prop-types.md
Labels: documentation
