Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-06, with the labels that each got.

#2240 New: jsx-curly-newline rule
  CHANGELOG.md
  docs/rules/jsx-curly-newline.md
  index.js
  lib/rules/jsx-curly-newline.js
  tests/lib/rules/jsx-curly-newline.js
Labels: new rule

#2300 [New]: `prop-types`: handle nested destructuring
  lib/util/usedPropTypes.js
  tests/lib/rules/no-unused-prop-types.js
  tests/lib/rules/prop-types.js
Labels: enhancement

#2303 [Docs] add `jsx-curly-newline` to README
  README.md
Labels: documentation

#2302 docs: fix typo
  README.md
Labels: documentation

#2314 Change reported range to only the identifier
  lib/rules/jsx-sort-props.js
  tests/lib/rules/jsx-sort-props.js
Labels: enhancement

#2316 fix(jsx-key): handle shorthand fragment syntax
  lib/rules/jsx-key.js
  tests/lib/rules/jsx-key.js
Labels: enhancement

#2320 [Fix] `prop-types`: fix crash on multiple destructuring
  lib/util/usedPropTypes.js
  tests/lib/rules/no-unused-prop-types.js
  tests/lib/rules/prop-types.js
Labels: bug
