Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-09, with the labels that each got.

#2375 [Fix] `no-unused-prop-types`: false positive with callback
  lib/util/Components.js
  lib/util/ast.js
  tests/lib/rules/destructuring-assignment.js
  tests/lib/rules/display-name.js
  tests/lib/rules/no-multi-comp.js
  tests/lib/rules/no-this-in-sfc.js
  tests/lib/rules/no-unused-prop-types.js
  tests/lib/rules/require-default-props.js
Labels: bug

#2261 [New] add `jsx-no-useless-fragment` rule
  README.md
  docs/rules/jsx-no-useless-fragment.md
  index.js
  lib/rules/jsx-no-useless-fragment.js
  lib/types.d.ts
  lib/util/jsx.js
  tests/lib/rules/jsx-no-useless-fragment.js
Labels: new rule

#2408 [New]`sort-comp`: add static-variables option
  docs/rules/sort-comp.md
  lib/rules/sort-comp.js
  tests/lib/rules/sort-comp.js
Labels: enhancement
