Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-11, with the labels that each got.

#2500 fix: wrong rule name
  docs/rules/jsx-first-prop-new-line.md
Labels: documentation

#2504 react/prop-types: Update 'skipUndeclared' in rule options
  docs/rules/prop-types.md
Labels: documentation

#2489 Fix documentation formatting in jsx-first-prop-new-line
  docs/rules/jsx-first-prop-new-line.md
Labels: documentation

#2478 feat(no-target-blank): Configure noreferrer requirement
  docs/rules/jsx-no-target-blank.md
  lib/rules/jsx-no-target-blank.js
  tests/lib/rules/jsx-no-target-blank.js
Labels: enhancement

#2419 [New] Add `jsx-no-script-url` to prevent usage of `javascript:` URLs
  CHANGELOG.md
  README.md
  docs/rules/jsx-no-script-url.md
  index.js
  lib/rules/jsx-no-script-url.js
  tests/lib/rules/jsx-no-script-url.js
Labels: new rule
