Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-03, with the labels that each got.

#2180 Added shared settings info, React version default note fix for #2169
  README.md
Labels: documentation

#2191 [new] Add jsx-props-no-spreading rule
  CHANGELOG.md
  README.md
  docs/rules/jsx-props-no-spreading.md
  index.js
  lib/rules/jsx-props-no-spreading.js
  tests/lib/rules/jsx-props-no-spreading.js
Labels: new rule

#2182 [jsx-sort-default-props] Bug fix for one case with spread
  lib/rules/jsx-sort-default-props.js
  tests/lib/rules/jsx-sort-default-props.js
Labels: bug
