Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-01, with the labels that each got.

#2103 Link does not end with '.'
  lib/util/version.js
Labels: documentation

#2109 Fix display-name false positive for React.memo
  lib/util/Components.js
  tests/lib/rules/display-name.js
Labels: bug

#2111 Fix issue with propTypes misclassifying props
  lib/util/propTypes.js
  tests/lib/rules/no-unused-prop-types.js
Labels: bug

#2113 [Fix] avoid crashing on self-closing fragments
  lib/rules/jsx-fragments.js
  tests/lib/rules/jsx-fragments.js
Labels: bug

#2114 update README
  README.md
Labels: documentation

#2115 Fix propType detection inside class bodies
  lib/util/propTypes.js
  tests/lib/rules/no-unused-prop-types.js
Labels: bug

#2117 fix: add a missing comma in the JSON settings
  README.md
Labels: documentation

#2125 Fix isPragmaComponentWrapper
  lib/util/Components.js
  tests/lib/rules/prop-types.js
Labels: bug

#2110 [new] Add prefer-read-only-props rule
  docs/rules/prefer-read-only-props.md
  index.js
  lib/rules/prefer-read-only-props.js
  tests/lib/rules/prefer-read-only-props.js
Labels: flow, new rule

#1945 Add state-in-constructor rule
  README.md
  docs/rules/state-in-constructor.md
  index.js
  lib/rules/no-direct-mutation-state.js
  lib/rules/state-in-constructor.js
  lib/util/Components.js
  lib/util/usedPropTypes.js
  tests/lib/rules/state-in-constructor.js
Labels: new rule

#2016 more friendly message for no-unescaped-entities
  docs/rules/no-unescaped-entities.md
  lib/rules/no-unescaped-entities.js
  tests/lib/rules/no-unescaped-entities.js
Labels: enhancement

#2116 Allow custom components in jsx-no-target-blank
  README.md
  docs/rules/jsx-no-target-blank.md
  lib/rules/jsx-no-target-blank.js
  lib/util/linkComponents.js
  tests/lib/rules/jsx-no-target-blank.js
  tests/util/.eslintrc
  tests/util/linkComponents.js
  tests/util/propWrapper.js
  tests/util/version.js
Labels: enhancement

#2143 Update jsx-fragments.md with fixable
  docs/rules/jsx-fragments.md
Labels: documentation
