Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-04, with the labels that each got.

#2227 [New] `jsx-indent`: Add `indentLogicalExpressions` option
  docs/rules/jsx-indent.md
  lib/rules/jsx-indent.js
  tests/lib/rules/jsx-indent.js
Labels: enhancement

#2225 [Fix] `display-name`: fix false negative around nested functions
  lib/rules/display-name.js
  tests/lib/rules/display-name.js
Labels: bug

#2230 [Fix] - Fix sorting props with numeric keys
  lib/rules/sort-prop-types.js
  tests/lib/rules/sort-prop-types.js
Labels: bug

#2233 implement flow version detection
  lib/util/version.js
  tests/fixtures/version/detect-version/node_modules/flow-bin/package.json
  tests/util/version.js
Labels: flow

#2193 [new] add static-property-placement rule
  README.md
  docs/rules/static-property-placement.md
  index.js
  lib/rules/display-name.js
  lib/rules/static-property-placement.js
  lib/util/props.js
  tests/lib/rules/static-property-placement.js
Labels: new rule

#2234 Validate boolean prop names nested deeper
  docs/rules/boolean-prop-naming.md
  lib/rules/boolean-prop-naming.js
  tests/lib/rules/boolean-prop-naming.js
Labels: enhancement

#2250 Make all jsx-prop-sort lints fixable
  lib/rules/jsx-sort-props.js
  tests/lib/rules/jsx-sort-props.js
Labels: enhancement
