Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2019-02, with the labels that each got.

#2151 Fix set state callback destructing & state use inside callback
  lib/rules/no-unused-state.js
  tests/lib/rules/no-unused-state.js
Labels: bug

#2160 Use syntax highlighting for examples in "no-access-state-in-setstate"
  docs/rules/no-access-state-in-setstate.md
Labels: documentation

#2167 Added check for template literals in no-string-refs rule
  docs/rules/no-string-refs.md
  lib/rules/no-string-refs.js
  tests/lib/rules/no-string-refs.js
Labels: enhancement, rule
