Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2020-10, with the labels that each got.

#2815 [Fix] `no-unused-prop-types`: Silence false positive on `never` type in TS
  CHANGELOG.md
  lib/rules/no-unused-prop-types.js
  tests/lib/rules/no-unused-prop-types.js
Labels: hacktoberfest, typescript

#2814 [Refactor] cleanup no-mixed-operators warnings
  .eslintrc
  lib/rules/destructuring-assignment.js
  lib/rules/forbid-foreign-prop-types.js
  lib/rules/jsx-indent.js
  lib/rules/jsx-max-depth.js
  lib/rules/jsx-one-expression-per-line.js
  lib/rules/no-set-state.js
  lib/rules/no-this-in-sfc.js
  lib/rules/no-unknown-property.js
  lib/rules/no-unused-state.js
  lib/rules/prefer-read-only-props.js
  lib/rules/prefer-stateless-function.js
  lib/rules/self-closing-comp.js
  lib/rules/sort-comp.js
  lib/rules/style-prop-object.js
  lib/util/propTypes.js
  lib/util/usedPropTypes.js
Labels: hacktoberfest

#2820 [Tests] `jsx-indent-props` : Apply indentation when used expression
  CHANGELOG.md
  tests/lib/rules/jsx-indent-props.js
Labels: hacktoberfest-accepted

#2835 [New]: `jsx-key`: added `checkKeyMustBeforeSpread` option for new jsx transform
  CHANGELOG.md
  docs/rules/jsx-key.md
  lib/rules/jsx-key.js
  tests/lib/rules/jsx-key.js
Labels: enhancement, hacktoberfest-accepted

#2693 [New]`jsx-newline`: Enforce a new line after jsx elements and expressions
  CHANGELOG.md
  README.md
  docs/rules/jsx-newline.md
  index.js
  lib/rules/jsx-newline.js
  tests/lib/rules/jsx-newline.js
Labels: new rule

#2763 [New] `jsx-no-constructed-context-values`: add rule for unstable context values
  CHANGELOG.md
  README.md
  docs/rules/jsx-no-constructed-context-values.md
  index.js
  lib/rules/jsx-no-constructed-context-values.js
  tests/lib/rules/jsx-no-constructed-context-values.js
Labels: new rule

#2843 [Fix] `prop-types`: function in class that returns a component causes false warning in typescript
  CHANGELOG.md
  lib/util/Components.js
  lib/util/propTypes.js
  tests/lib/rules/prop-types.js
Labels: hacktoberfest-accepted, typescript
