Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2020-09, with the labels that each got.

#2772 [Fix] `prefer-read-only-props`: support Flow `$ReadOnly`
  CHANGELOG.md
  lib/rules/prefer-read-only-props.js
  tests/lib/rules/prefer-read-only-props.js
Labels: flow

#2782 [New] `jsx-no-literals`: add `noAttributeStrings` option
  CHANGELOG.md
  docs/rules/jsx-no-literals.md
  lib/rules/jsx-no-literals.js
  tests/lib/rules/jsx-no-literals.js
Labels: enhancement

#1689 Issue #1686 - jsx-handler-names: false positive when handler name begins with number
  lib/rules/jsx-handler-names.js
  tests/lib/rules/jsx-handler-names.js
Labels: bug
