Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2020-02, with the labels that each got.

#2560 Fix crash on TSEmptyBodyFunctionExpression AST node
  lib/util/usedPropTypes.js
  tests/lib/rules/no-unused-prop-types.js
Labels: typescript

#2568 Small visual inconsistency in README.md
  README.md
  lib/rules/jsx-curly-newline.js
Labels: documentation

#2572 [Fix] `self-closing-comp`: consider JSXMemberExpression as component too
  docs/rules/self-closing-comp.md
  lib/rules/self-closing-comp.js
  tests/lib/rules/self-closing-comp.js
Labels: bug

#1819 [New] `style-prop-object`: Add `allow` option
  docs/rules/style-prop-object.md
  lib/rules/style-prop-object.js
  tests/lib/rules/style-prop-object.js
Labels: enhancement, rule

#2292 Change the reporting for no-unused-prop-types
  lib/rules/no-unused-prop-types.js
  tests/lib/rules/no-unused-prop-types.js
Labels: flow
