Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2020-05, with the labels that each got.

#2633 Add Rules of Hooks to Other useful plugins section
  README.md
Labels: documentation

#2615 Allow a custom message with forbid props
  docs/rules/forbid-component-props.md
  docs/rules/forbid-dom-props.md
  lib/rules/forbid-component-props.js
  lib/rules/forbid-dom-props.js
  tests/lib/rules/forbid-component-props.js
  tests/lib/rules/forbid-dom-props.js
Labels: enhancement

#2610 [Fix] `jsx-key`: support optional chaining
  lib/rules/jsx-key.js
  tests/lib/rules/jsx-key.js
Labels: bug

#2635 [New] support eslint v7
  .travis.yml
  package.json
  tests/lib/rules/forbid-prop-types.js
  tests/lib/rules/jsx-closing-bracket-location.js
  tests/lib/rules/jsx-curly-brace-presence.js
  tests/lib/rules/jsx-indent.js
  tests/lib/rules/jsx-sort-props.js
  tests/lib/rules/jsx-uses-vars.js
  tests/lib/rules/no-typos.js
  tests/lib/rules/no-unknown-property.js
  tests/lib/rules/prefer-read-only-props.js
Labels: enhancement

#2546 Document that rules dealing with prop types recognize static types, too
  docs/rules/boolean-prop-naming.md
  docs/rules/default-props-match-prop-types.md
  docs/rules/no-unused-prop-types.md
  docs/rules/prop-types.md
  docs/rules/require-default-props.md
  docs/rules/sort-prop-types.md
Labels: documentation, flow, typescript
