Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2020-01, with the labels that each got.

#2532 feat(require-default-props): add option to ignore functional components
  CHANGELOG.md
  docs/rules/require-default-props.md
  lib/rules/require-default-props.js
  tests/lib/rules/require-default-props.js
Labels: enhancement

#2540 Fix title for "no-render-return-value" rule docs
  docs/rules/no-render-return-value.md
Labels: documentation

#2414 React/declarations for function components
  CHANGELOG.md
  docs/rules/function-component-definition.md
  index.js
  lib/rules/function-component-definition.js
  tests/lib/rules/function-component-definition.js
Labels: new rule

#2536 [Fix]: false positives for `no-unused-...` when using TS type assertions
  lib/rules/no-unused-state.js
  lib/util/ast.js
  lib/util/usedPropTypes.js
  tests/lib/rules/no-unused-prop-types.js
  tests/lib/rules/no-unused-state.js
Labels: typescript

#2547 Fix typo `jsx-props-no-spreading` document
  docs/rules/jsx-props-no-spreading.md
Labels: documentation

#1742 [Docs] Re-sort all rules alphabetically
  .travis.yml
  README.md
  lib/rules/void-dom-elements-no-children.js
  markdown.config.js
  package.json
Labels: documentation
