Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2020-03, with the labels that each got.

#2582 [fix] `prefer-stateless-function`: avoid crash on ts empty constructor
  lib/rules/prefer-stateless-function.js
  tests/lib/rules/prefer-stateless-function.js
Labels: bug, typescript

#2146 [New]: `jsx-no-literals`: add `ignoreProps` option to ignore props validation
  docs/rules/jsx-no-literals.md
  lib/rules/jsx-no-literals.js
  tests/lib/rules/jsx-no-literals.js
Labels: enhancement

#2608 Fix unnamedComponents option examples in function-component-definition documentation
  docs/rules/function-component-definition.md
Labels: documentation
