Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2021-11, with the labels that each got.

#2863 [New] add `no-invalid-html-attribute` rule
  CHANGELOG.md
  README.md
  docs/rules/no-invalid-html-attribute.md
  index.js
  lib/rules/no-invalid-html-attribute.js
  tests/lib/rules/no-invalid-html-attribute.js
Labels: new rule

#3141 [readme] fix syntax typo
  CHANGELOG.md
  README.md
Labels: documentation

#3129 [New] `function-component-definition`: support `namedComponents` option being an array
  CHANGELOG.md
  docs/rules/function-component-definition.md
  lib/rules/function-component-definition.js
  tests/lib/rules/function-component-definition.js
Labels: enhancement
