Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2021-08, with the labels that each got.

#3018 [Docs] `jsx-uses-react`, `react-in-jsx-scope`: document `react/jsx-runtime` config
  CHANGELOG.md
  README.md
  docs/rules/jsx-uses-react.md
  docs/rules/react-in-jsx-scope.md
Labels: documentation

#2994 Fixing small typo on require-default-props docs
  CHANGELOG.md
  docs/rules/require-default-props.md
Labels: documentation

#1547 [New] add `prefer-exact-props` rule
  CHANGELOG.md
  README.md
  docs/rules/prefer-exact-props.md
  index.js
  lib/rules/prefer-exact-props.js
  lib/util/propWrapper.js
  tests/lib/rules/prefer-exact-props.js
  tests/util/propWrapper.js
Labels: enhancement, new rule

#1617 jsx-no-target-blank to check for forms with target="_blank"
  CHANGELOG.md
  README.md
  docs/rules/jsx-no-target-blank.md
  lib/rules/jsx-no-target-blank.js
  lib/util/linkComponents.js
  tests/lib/rules/jsx-no-target-blank.js
Labels: enhancement

#1903 [New] `no-children-prop`: Add `allowFunctions` option
  CHANGELOG.md
  docs/rules/no-children-prop.md
  lib/rules/no-children-prop.js
  tests/lib/rules/no-children-prop.js
Labels: enhancement

#3048 jsx-no-bind: Report usage of local functions as violations
  CHANGELOG.md
  docs/rules/jsx-no-bind.md
  lib/rules/jsx-no-bind.js
  tests/lib/rules/jsx-no-bind.js
Labels: bug

#3049 [Fix] `prop-types`, `propTypes`: handle React.* TypeScript types
  CHANGELOG.md
  lib/util/propTypes.js
  tests/lib/rules/prop-types.js
Labels: bug, typescript
