Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2022-10, with the labels that each got.

#3445 [Docs] `no-unknown-property`: fix typo in link
  CHANGELOG.md
  docs/rules/no-unknown-property.md
Labels: documentation

#3451 [Perf] improve performance by optimizing getId
  CHANGELOG.md
  lib/util/Components.js
Labels: hacktoberfest-accepted

#3444 [Docs] `no-unstable-nested-components`: Warn about memoized, nested components
  CHANGELOG.md
  docs/rules/no-unstable-nested-components.md
  tests/lib/rules/no-unstable-nested-components.js
Labels: documentation

#3449 [New] `hook-use-state`: add `allowDestructuredState` option
  CHANGELOG.md
  docs/rules/hook-use-state.md
  lib/rules/hook-use-state.js
  tests/lib/rules/hook-use-state.js
Labels: enhancement

#3429 [New] support new config system
  CHANGELOG.md
  README.md
  configs/all.js
  configs/jsx-runtime.js
  configs/recommended.js
  index.js
Labels: enhancement

#3459 [Perf] component detection: improve performance by avoiding traversing parents unnecessarily
  CHANGELOG.md
  lib/util/Components.js
  tests/lib/rules/destructuring-assignment.js
Labels: hacktoberfest-accepted

#2848 [New] add `no-object-type-as-default-prop` rule
  CHANGELOG.md
  README.md
  configs/all.js
  docs/rules/no-object-type-as-default-prop.md
  lib/rules/no-object-type-as-default-prop.js
  tests/lib/rules/no-object-type-as-default-prop.js
Labels: new rule

#3473 docs: inclusive language w/ allowlist
  CHANGELOG.md
  docs/rules/forbid-component-props.md
Labels: documentation, hacktoberfest-accepted
