Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2022-03, with the labels that each got.

#3241 [Fix] `boolean-prop-naming`: handle React.FC, intersection, union types
  CHANGELOG.md
  lib/rules/boolean-prop-naming.js
  tests/lib/rules/boolean-prop-naming.js
Labels: bug, flow, typescript

#3235 [New] `destructuring-assignment`: add option `destructureInSignature`
  CHANGELOG.md
  README.md
  docs/rules/destructuring-assignment.md
  lib/rules/destructuring-assignment.js
  tests/lib/rules/destructuring-assignment.js
Labels: enhancement

#3251 [New] `no-unknown-property`: Allow crossOrigin on image tag (SVG)
  CHANGELOG.md
  lib/rules/no-unknown-property.js
  tests/lib/rules/no-unknown-property.js
Labels: enhancement

#3254 [readme] remove global usage and eslint version from readme
  CHANGELOG.md
  README.md
Labels: documentation
