Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2022-02, with the labels that each got.

#3195 Handle TSTypeReference in no-unused-prop-types
  CHANGELOG.md
  lib/util/propTypes.js
  tests/lib/rules/no-unused-prop-types.js
Labels: typescript

#2753 [New] add `iframe-missing-sandbox` rule (migrate rule from TSLint)
  CHANGELOG.md
  README.md
  docs/rules/iframe-missing-sandbox.md
  index.js
  lib/rules/iframe-missing-sandbox.js
  tests/lib/rules/iframe-missing-sandbox.js
Labels: new rule

#620 Fix indentation of closing parentheses
  CHANGELOG.md
  lib/rules/jsx-indent.js
  tests/lib/rules/jsx-indent.js
Labels: bug, help wanted

#1691 Issue #1632 - jsx-sort-props: reservedFirst conflicts with callbacksLast
  tests/lib/rules/jsx-sort-props.js
Labels: help wanted

#3198 [New] `jsx-sort-props`: support multiline prop groups
  CHANGELOG.md
  docs/rules/jsx-sort-props.md
  lib/rules/jsx-sort-props.js
  tests/lib/rules/jsx-sort-props.js
Labels: enhancement

#3199 Get rid of red in jsx-no-target-blank documentation
  CHANGELOG.md
  docs/rules/jsx-no-target-blank.md
Labels: documentation

#3202 [Docs] `jsx-key`: improve example
  CHANGELOG.md
  docs/rules/jsx-key.md
Labels: documentation
