Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2023-06, with the labels that each got.

#3582 [Fix] update configuration URL
  CHANGELOG.md
  README.md
Labels: bug, documentation

#3583 [Fix] `destructuring-assignment`: remove `useContext` destructuring check
  CHANGELOG.md
  lib/rules/destructuring-assignment.js
  tests/lib/rules/destructuring-assignment.js
Labels: bug

#3581 Reword jsx-no-bind rationale
  CHANGELOG.md
  docs/rules/jsx-no-bind.md
Labels: documentation
