Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2024-02, with the labels that each got.

#3679 [Fix] `prop-types`: handle nested forwardRef + memo
  CHANGELOG.md
  lib/rules/prop-types.js
  tests/lib/rules/prop-types.js
Labels: bug

#3690 [Docs] fix link to iframe attribute on mdn
  CHANGELOG.md
  docs/rules/iframe-missing-sandbox.md
Labels: documentation

#3680 [New] add `checked-requires-onchange-or-readonly` rule
  CHANGELOG.md
  README.md
  docs/rules/checked-requires-onchange-or-readonly.md
  lib/rules/checked-requires-onchange-or-readonly.js
  lib/rules/index.js
  tests/lib/rules/checked-requires-onchange-or-readonly.js
Labels: enhancement, new rule
