Repository jsx-eslint/eslint-plugin-react, pull requests merged in 2024-09, with the labels that each got.

#3817 [Docs] `no-danger`: update broken link
  CHANGELOG.md
  docs/rules/no-danger.md
Labels: documentation

#3667 [New] `forward-ref-uses-ref`: add rule for checking ref parameter is added
  CHANGELOG.md
  README.md
  docs/rules/forward-ref-uses-ref.md
  lib/rules/forward-ref-uses-ref.js
  lib/rules/index.js
  tests/lib/rules/forward-ref-uses-ref.js
Labels: new rule

#3831 [New] Add suggestions to `no-unescaped-entities`
  CHANGELOG.md
  README.md
  docs/rules/no-unescaped-entities.md
  lib/rules/no-unescaped-entities.js
  tests/lib/rules/no-unescaped-entities.js
Labels: enhancement

#3805 [New] `forbid-component-props`: add `allowedForPatterns` and `disallowedForPatterns` options
  CHANGELOG.md
  docs/rules/forbid-component-props.md
  lib/rules/forbid-component-props.js
  tests/lib/rules/forbid-component-props.js
Labels: enhancement

#3824 [readme] flat config example for react 17+
  CHANGELOG.md
  README.md
Labels: documentation

#3834 [readme] Fix shared settings link
  CHANGELOG.md
  README.md
Labels: documentation
